openapi: 3.0.1
info:
  title: Simple Product API
  description: Simple Product API for creating products
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: product
  description: the product API
paths:
  /product:
    post:
      tags:
      - product
      summary: Create a product
      operationId: productPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDetails'
            examples:
              SUCCESS:
                value:
                  name: iPhone 12
                  price: 515.99
                  type: ELECTRONICS
                  description: Latest iPhone model
        required: true
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples:
                SUCCESS:
                  value:
                    name: iPhone 12
                    price: 515.99
                    type: ELECTRONICS
                    id: 1
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
components:
  schemas:
    Product:
      allOf:
        - required:
          - id
          type: object
          properties:
            id:
              type: integer
              format: int32
        - $ref: '#/components/schemas/ProductDetails'
    ProductDetails:
      required:
        - name
        - price
        - type
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: float
        type:
          type: string
          enum:
          - ELECTRONICS
          - CLOTHING
          - FURNITURE
        description:
          type: string
    BadRequestError:
      required:
      - error
      - path
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int32
        error:
          type: string
        path:
          type: string
